language: cpp

compiler: g++

before_script:
  - svn checkout https://github.com/philsquared/Catch/trunk/single_include/
  - CATCH_PATH=`pwd`/single_include/
  - WECORE_SRC=`pwd`

  - echo $WECORE_SRC
  - echo $CATCH_PATH

  - ls -lR

script:
  - make
