language: cpp

dist: trusty

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5

compiler:
  - g++
  - clang

before_script:
  - curl "https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp" --create-dirs -o "single_include/catch.hpp"

script:
  - make

after_success:
  - ./WECoreTest
