language: cpp

dist: trusty

compiler:
  - g++
  - clang

before_script:
  - curl "https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp" --create-dirs -o "single_include/catch.hpp"

script:
  - make

after_success:
  - ./WECoreTest
