language: cpp

dist: trusty

compiler:
  - g++
  - clang

before_script:
  - svn checkout https://github.com/philsquared/Catch/trunk/single_include/

script:
  - make

after_success:
  - ./WECoreTest
